import Head from 'next/head'
import { Footer } from '../components/Footer'
import { Headline } from '../components/Headline'
import { Link } from '../components/Link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline page="about" />
        <Link />
      </main>

      <Footer />
    </div>
  )
}
